services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'bridge'

    ports:
      - 8096:8096

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/guidje/Vídeos/Filmes:/media/movies:ro
      - /home/guidje/Vídeos/Seriados:/media/tvshows:ro

    restart: unless-stopped

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility

    gpus: all

